# Generated by Django 5.0 on 2025-02-17 20:36
import logging
from django.db import migrations

logger = logging.getLogger(__name__)


def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    user = get_user_model()

    PASSWORD = USERNAME = "admin"
    EMAIL = "admin@example.com"

    if not user.objects.filter(username=USERNAME, email=EMAIL).exists():
        logger.info("Creating new superuser")
        admin = user.objects.create_superuser(
            username=USERNAME, password=PASSWORD, email=EMAIL
        )
        admin.save()
    else:
        logger.info("Superuser already created!")


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [migrations.RunPython(generate_superuser)]
